FROM python:latest
RUN mkdir /home/txkj
WORKDIR /home/txkj
COPY ./scripts /home/txkj/scripts

RUN pip install -i https://pypi.douban.com/simple \
    flask\
    matplotlib\
    seaborn\
    sklearn\
    gevent\
    prettytable\
    opencv-python\
    JoUtil==1.0.5\
    requests

RUN echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye main contrib non-free" > /etc/apt/sources.list \
&& echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-updates main contrib non-free" >> /etc/apt/sources.list \
&& echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-backports main contrib non-free" >> /etc/apt/sources.list \
&& echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian-security bullseye-security main contrib non-free" >> /etc/apt/sources.list \
&& apt-get clean \
&& apt-get update \
&& apt-get install vim -y && apt-get install libglib2.0-0 -y && apt install libgl1-mesa-glx -y && apt-get install gcc -y && apt autoclean -y && apt autoremove -y && rm -rf /var/lib/apt/lists/*


RUN chmod 777 /home/txkj ./ -R

CMD ["/home/txkj/scripts/start_server.sh"]

# docker run  -p 11145:11145 -v /home/ldq/docker_file/map_depot/data:/usr/data  -e img_dir=/usr/data -e port=11145 -e ip=192.168.3.221 -it map_depot:v0.0.9 /bin/bash




