FROM python:latest
RUN mkdir /home/txkj
WORKDIR /home/txkj
COPY ./scripts /home/txkj/scripts

# 操作速度太慢，https://yijiebuyi.com/blog/f03488dcc97ce9d0f0fdbcfce3d4a07b.html#apt-get-update-%E5%A4%AA%E6%85%A2%E5%A6%82%E4%BD%95%E6%8D%A2%E6%BA%90
RUN apt-get update && apt-get install vim -y

# && apt-get install libglib2.0-0 -y && apt install libgl1-mesa-glx -y && apt-get install gcc -y && apt autoclean -y && apt autoremove -y && rm -rf /var/lib/apt/lists/*

RUN pip install -i https://pypi.douban.com/simple \
    flask\
    matplotlib\
    seaborn\
    sklearn\
    gevent\
    prettytable\
    opencv-python\
    JoUtil==1.0.5

CMD ["/home/txkj/scripts/start_server.sh"]






